import type { Metadata } from 'next';

import { PARTNERS, PARTNER_ORDER } from '@/lib/partners';

export const metadata: Metadata = {
  title: 'Legal — Misfit Mason',
  description: 'Leaderboard rules, affiliate disclosure, terms and responsible gambling.',
};

/**
 * Deliberately plain, and deliberately careful: nothing on this site may imply
 * that gambling is profitable or that any outcome is likely.
 */
export default function LegalPage() {
  return (
    <section className="section wrap" style={{ paddingTop: 40 }}>
      <div className="section-head">
        <h1 className="h-page">Legal</h1>
      </div>

      <div className="prose">
        <h2 id="rules">Leaderboard rules</h2>
        <ul>
          {PARTNER_ORDER.map((id) => (
            <li key={id}>
              <strong>{PARTNERS[id].name}</strong> — a ${PARTNERS[id].prizePool} pool{' '}
              {PARTNERS[id].comingSoon
                ? 'with the split to be announced before it opens.'
                : `paid ${PARTNERS[id].prizeTable.map((p) => `$${p}`).join(' / ')} to the top ${PARTNERS[id].prizeTable.length}.`}
            </li>
          ))}
          <li>Ranking is on total amount wagered during the period, not weighted by house edge.</li>
          <li>No minimum wager is required to qualify.</li>
          <li>
            Entry requires an account registered through this site&apos;s referral links. Accounts
            opened under another affiliate cannot be transferred.
          </li>
          <li>Periods run for the calendar month, resetting at 00:00 UTC on the 1st.</li>
          <li>
            Standings come from each casino&apos;s own reporting and may lag or be corrected. Final
            placings are taken from the casino&apos;s figures at period close.
          </li>
          <li>
            <strong>No wager abuse.</strong> Low-risk, hedged or zero-edge play used only to inflate
            a wagered total does not count toward standings and will be removed from the board.
          </li>
          <li>
            Multiple accounts, collusion, chargebacks or bonus abuse void any prize, at
            MisfitMason&apos;s discretion.
          </li>
          <li>Prizes are paid within a reasonable period after a board closes.</li>
          <li>Prize pools and splits may change for future periods. Changes are not retroactive.</li>
          <li>
            <strong>MisfitMason has the final say</strong> on standings, eligibility, disputes and
            prize decisions.
          </li>
        </ul>

        <h2 id="affiliate">Affiliate disclosure</h2>
        <p>
          Misfit Mason is an affiliate of the casinos listed on this site. Registering through our
          links or codes means those operators pay us a share of the revenue generated by your play.
          This is how the site is funded and it costs you nothing extra.
        </p>
        <p>
          Our stated policy is that <strong>100% of that affiliate revenue is returned</strong> to
          the players who generated it. Leaderboard prizes are funded separately and personally by
          MisfitMason. We do not operate any casino, we do not hold your funds, and we cannot
          influence any game outcome.
        </p>

        <h2 id="terms">Terms</h2>
        <ul>
          <li>
            This site provides information and community leaderboards. It is not a gambling
            operator.
          </li>
          <li>
            You must be at least <strong>18 years old</strong>, and old enough to gamble legally
            where you live, to take part.
          </li>
          <li>
            Checking that the linked operators are lawful in your jurisdiction is your
            responsibility. Some are restricted or prohibited in some countries.
          </li>
          <li>
            Rewards and prizes are discretionary and may be withheld where rules have been broken or
            where paying them would be unlawful.
          </li>
          <li>
            Figures displayed are provided in good faith from third-party data and are not a
            statement of account.
          </li>
        </ul>

        <h2 id="responsible">Responsible gambling</h2>
        <p>
          Gambling carries real risk and most people lose money over time. Nothing here is advice, a
          prediction, or a suggestion that gambling is a way to make money. Leaderboard prizes and
          affiliate returns do not change the odds of any game.
        </p>
        <ul>
          <li>Only stake money you can afford to lose entirely.</li>
          <li>Never chase losses, and never gamble to solve a financial problem.</li>
          <li>Use the deposit limits, time-outs and self-exclusion tools your operator provides.</li>
        </ul>
        <p>
          If gambling is causing you harm, free and confidential help is available.{' '}
          <a href="https://www.begambleaware.org" target="_blank" rel="noreferrer">
            BeGambleAware
          </a>{' '}
          and{' '}
          <a href="https://www.gamcare.org.uk" target="_blank" rel="noreferrer">
            GamCare
          </a>
          , or the National Gambling Helpline on 0808 8020 133.
        </p>

        <p className="pending">Drafted for review. This is not legal advice.</p>
      </div>
    </section>
  );
}
